Develop
GlebShulga/todo_task pull request #1
Opened 2021-09-02 23:24 UTC by GlebShulga

Many changes

2021-09-03 08:52 UTC, NurAliia requested changes

2021-09-03 08:52 UTC, NurAliia commented on server/server.js
> +        if (categoryId === undefined || categoryId === "") {
Можно эту проверку вынести в отдельную функцию в helpers. isEmpty(value) => {}

2021-09-03 08:52 UTC, NurAliia commented on src/components/Category/Category.jsx
> +            <CreateCategory
Может назвать компонент modal  ?

2021-09-03 08:52 UTC, NurAliia commented on src/components/Category/Category.jsx
> +          {!isEditingTaskMode ? (
Данная тернарка слишком большая, лучше вынести ее части в константы и тут использовать уже их

2021-09-03 08:52 UTC, NurAliia commented on src/components/Category/Category.jsx
> +        children.map((child) => (
в константу

2021-09-03 08:52 UTC, NurAliia commented on src/components/CategoryList/CategoryList.jsx
> +      {rootCategories.map((category) => {
в константу

2021-09-03 08:52 UTC, NurAliia commented on src/components/EditTask/EditTask.jsx
> +          checked={status === "done"}
думаю лучше вынести проверку в функцию isChecked

2021-09-03 08:52 UTC, NurAliia commented on src/components/EditTask/EditTask.scss
> +display: flex;
отступы

2021-09-03 08:52 UTC, NurAliia commented on src/components/ProgressBar/ProgressBar.jsx
> +  const commonTaskData = Object.values(
мне кажется весь подсчет можно заменить на один foreach, а котором подсчитать count и isDone . И потом (isDone / count) * 100

2021-09-03 08:52 UTC, NurAliia commented on src/components/ProgressBar/ProgressBar.jsx
> +      <div style={{ width: `${choosenCategoryResult}%` }} className="filler">
Есть html тег 
`progress`

2021-09-03 08:52 UTC, NurAliia commented on server/base/taskList.json
> -  {
check

2021-09-03 08:56 UTC, GlebShulga commented on src/components/Category/Category.jsx
> +            <CreateCategory
А я его два раза использую.
input над списком категорий - это тот же самый компонент. Было написано, что добавление категории по кнопке + на моё усмотрение и я просто сэкономил время.
![Screenshot from 2021-08-30 20-29-01](https://user-images.githubusercontent.com/67621167/131978861-0b8c961c-2902-45f3-afc6-776ffeb61134.png)

2021-09-03 09:39 UTC, NurAliia commented on src/components/Category/Category.jsx
> +            <CreateCategory
Ага, я заметила. но я бы все равно вынесла в комопнент modal, потому что сейчас CreateCategory принимает не относящийся по смыслу к нему пропс, а именно isCreateTaskModalOpen

2021-09-03 21:44 UTC, GlebShulga commented on src/components/EditTask/EditTask.jsx
> +          checked={status === "done"}
Fixed. Commit - 24dd5d6

2021-09-04 05:50 UTC, KalebNiven commented on src/components/Category/Category.jsx
> +          {!isEditingTaskMode ? (
А что если я превращу эту тернарку в неТернарку и не буду ничего никуда выносить. Это критично?
![Screenshot 2021-08-30](https://user-images.githubusercontent.com/16971223/132084182-2346c720-8b2e-4f81-9eec-f1561f3fe29e.png)

2021-09-04 05:52 UTC, GlebShulga commented on src/components/Category/Category.jsx
> +          {!isEditingTaskMode ? (
А что если я превращу тернарку в неТернарку и не буду ничего никуда выносить. Это критично?
![Screenshot 2021-08-30](https://user-images.githubusercontent.com/67621167/132084238-e2202409-1a5c-47a6-9a6f-06505f7c5d21.png)

2021-09-04 05:59 UTC, GlebShulga commented on src/components/Category/Category.jsx
> +        children.map((child) => (
fixed. commit - be8072b

2021-09-04 06:19 UTC, GlebShulga commented on src/components/ProgressBar/ProgressBar.jsx
> +      <div style={{ width: `${choosenCategoryResult}%` }} className="filler">
fixed. comment - 0cdfe84

2021-09-04 06:20 UTC, GlebShulga commented on src/components/Category/Category.jsx
> +            <CreateCategory
А как же в таком случае переиспользование компонентов? Перейду на редакс, вопрос с пропсами уйдет.

2021-09-05 21:22 UTC, GlebShulga commented on server/server.js
> +        if (categoryId === undefined || categoryId === "") {
fixed. commit - dc2a06f

2021-09-07 02:06 UTC, GlebShulga commented on src/components/EditTask/EditTask.scss
> +display: flex;
fixed

2021-09-08 10:16 UTC, GlebShulga commented on src/components/ProgressBar/ProgressBar.jsx
> +  const commonTaskData = Object.values(
fixed. commit - db5f054

2021-09-08 15:34 UTC, NurAliia commented on src/components/Category/Category.jsx
> +          {!isEditingTaskMode ? (
так ок

2021-09-08 21:21 UTC, GlebShulga commented on src/components/Category/Category.jsx
> +          {!isEditingTaskMode ? (
fixed. commit - 532091e

2021-09-13 08:29 UTC, merged